### ISSUE TITLE
`strerror_r` check is incorrect

### ISSUE THREAD

**Issue by lambda-fairy** [lambda-fairy/rust-errno#45]
@A1-Triard:

> By the way, looks like this is not 100%-correct `strerror_r` result check. The `strerror_r` Linux manpage says, that starting from glibc 2.13 it returns (positive) errno as a result instead of returning `-1` and setting `errno`. The corresponding manpage in FreeBSD also specifies `0`, `EINVAL`, and `ERANGE` as only possible return values.

https://linux.die.net/man/3/strerror_r

Thinking further, the fact that a `Display` impl (which most people assume is non–side-effecting) can change global state is kind of surprising. We'll need to document that at least. Not sure what else we should do.

**Comment by A1-Triard** [comment]
> Not sure what else we should do.

You can restore old errno value, but personally I would not bother with that.
